dist: bionic
group: travis_latest

language:
  - c

compiler:
  - gcc

os:
  - linux

addons:
  apt:
    packages:
      - gcovr
      - doxygen
      - python3-pip

branches:
  only:
    - master

notifications:
  email:
    on_success: never
    on_failure: always

install:
  - pip3 install --user $(whoami) --upgrade pip
  - pip3 install --user $(whoami) meson ninja

script:
  - meson build -Db_coverage=true
  - cd build
  - meson test
  - ninja generate-docs
  - ninja coverage

after_success:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git add docs
  - git commit -m "Travis build - $TRAVIS_BUILD_NUMBER"
  - git remote add origin-pages https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG} > /dev/null 2>&1
  - git push origin-master
